### PR TITLE
smaller "features" added

### PR DESCRIPTION
**Pull request by ppetermann**
This PR basically introduces two environment variables:

**SEAT_PLUGIN_REPOSITORY** for your .env file - this translates to a `composer config repositories.extra ${SEAT_PLUGIN_REPOSITORY}` call, thus allowing to add an own repository. A typical example would be to add a composer VCS repository, to install a private plugin:
```
SEAT_PLUGIN_REPOSITORY={"type":"vcs","url":"https://github.com/my-username/my-seat-plugin"}
```
note that if the repository needs authentication, you'll need to pass composers COMPOSER_AUTH variable too. For github this would be:
```
COMPOSER_AUTH={"github-oauth": {"github.com": "YOURTOKENHERE"}}
```
refer to composers documentation for more information on repositories and authentication.

**PHP_OPTIONS** for seat-app to be configured in your docker-compose.yml - this will be passed to php-fpm, and allows to define additional configuration for PHP, such as modifying the max_execution_time
```
 seat-app:
    image: eveseat/eveseat-app:latest
    container_name: seat-app
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
      PHP_OPTIONS: "-d max_execution_time=120"
    ...
```

### CODE REVIEW

**Review by herpaderpaldent — CHANGES_REQUESTED** [review]
Hey @ppetermann 

You should consider adding your PR here: https://github.com/eveseat/scripts

Think about https://github.com/eveseat/scripts/blob/master/docker-compose/.env and how to add such a private repo to the `.env`.

**Comment by ppetermann** [comment]
Not sure if I understand? 
* there is no change for eveseat/scripts, the only thing that could be the example I gave in the PR's description, I assumed who ever merged would that copy to the docs, where it belongs
* don't get the second part at all, because thats exactly what I described in the PR what is there to think about?

**Comment by leonjza** [comment]
Thanks for the PR!

Just to make 100% sure I understand this, simply having `COMPOSER_AUTH` defined as an environment variable would be sufficient for the authenticated use case?

> note that if the repository needs authentication, you'll need to pass composers COMPOSER_AUTH variable too. For github this would be:

As for @herpaderpaldent 's comments, the scripts repo has a dev environment script to setup this stuff, and I think the suggestion is simply to add it here too if needed.

**Comment by herpaderpaldent** [comment]
This not only regards development but also productive setups via bash-script:

https://raw.githubusercontent.com/eveseat/scripts/master/docker-compose/bootstrap.sh 

```
echo "Grabbing docker-compose and .env file"
curl -L https://raw.githubusercontent.com/eveseat/scripts/master/docker-compose/docker-compose.yml -o $SEAT_DOCKER_INSTALL/docker-compose.yml
curl -L https://raw.githubusercontent.com/eveseat/scripts/master/docker-compose/.env -o $SEAT_DOCKER_INSTALL/.env
curl -L https://raw.githubusercontent.com/eveseat/scripts/master/docker-compose/my.cnf -o $SEAT_DOCKER_INSTALL/my.cnf
``` 

In my opinion any change to the docker.yml should be brought forward to be used by users via the `.env` from scripts

Also this looks like only one private repo could be added. Can you extend it to support n private repos?

**Comment by ppetermann** [comment]
@leonjza well, the environment within your container - thus putting it in the .env file next to the SEAT_PLUGIN_REPOSITORY will do the job - but its really a default composer behavior, not something i've added. see https://getcomposer.org/doc/03-cli.md#composer-auth

@herpaderpaldent docker.yml? uhm the SEAT_PLUGIN_REPOSITORY is what you add to the .env file if you want to make use of it, so all that could be added would be an example to the .env
and basically for the PHP_OPTIONS its similarly true - the docker-compose.yml in scripts could have an example added, but I wouldn't even know what options to set as an example, as this is basically a tuning flag that you can use to customize the PHP settings of the container. 

In both cases the actual changes implementing this are in this PR, as they *need* to be against the startup script of the container.

As for the example: I think adding this to the documentation is the better place than adding the examples without much explanations to the .env or the docker-compose.yml

**Comment by ppetermann** [comment]
its been a month, hence I'll assume this won't be accepted anymore.

**Comment by herpaderpaldent** [comment]
IMHO: All of us got limited time and this PR was not on this highest priority. That doesn't mean it would not have been merged at some point. 
F.e. i have PRs open since the 8th of november ...

**Comment by ppetermann** [comment]
well, as you said, all of us got limited time; 

I've spent more time answering on the comments here and trying to have a conversation with you about this exact PR on slack, then it should take to review whats literally 8 lines, mostly configuration. Now don't get me wrong, that's totally OK, but at some point, I want the PR off my table, so I don't have to pay attention to it anymore, and for the size (8 lines) and impact it has (adding "features" that apparently nobody but me needs), the amount of a month seems fair to me.

Now, If you still want the contents, I haven't removed the fork, and its still public, but don't expect me to spend more time on this, as I've moved on into pushing my own forked image to docker-hub and use that in my live setup now.

Hence: closing doesn't mean you can't have the change anymore, it simply means I won't spend time into answering questions about it anymore.

**Pull request closed without merging**
